#!/usr/bin/env node
/**
 * Simulated testing session — an end-to-end exercise of every subsystem.
 *
 *   node scripts/demo-session.mjs [--state <dir>] [--emit <dir>]
 *
 * This is NOT a test of any real software. It is a harness that drives the engines through
 * a realistic sequence so that:
 *
 *   1. the whole pipeline is exercised together, not just unit by unit;
 *   2. the example artefacts under examples/artifacts are GENERATED by the system rather
 *      than hand-written to look plausible.
 *
 * The scenario deliberately includes the awkward cases: a claim that gets downgraded for
 * lack of evidence, a blocked branch that does not stop the session, a duplicate finding, an
 * unconfirmed external write, and an interrupted execution.
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { setStateRoot } from '../engine/core/paths.mjs';

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] && !process.argv[i + 1].startsWith('--') ? process.argv[i + 1] : fallback;
}

const stateDir = arg('state') ?? fs.mkdtempSync(path.join(os.tmpdir(), 'ast-demo-'));
setStateRoot(stateDir);

const state = await import('../engine/state-engine/index.mjs');
const risk = await import('../engine/risk-engine/index.mjs');
const applicability = await import('../engine/applicability-engine/index.mjs');
const browser = await import('../engine/browser-decision/index.mjs');
const decisions = await import('../engine/decision-engine/index.mjs');
const evidence = await import('../engine/evidence-engine/index.mjs');
const execution = await import('../engine/execution-engine/index.mjs');
const defects = await import('../engine/defect-engine/index.mjs');
const uncertainty = await import('../engine/uncertainty-register/index.mjs');
const auth = await import('../engine/authorization/index.mjs');
const reporting = await import('../engine/reporting-engine/index.mjs');
const { query } = await import('../engine/traceability/index.mjs');

const GIT = { repository: 'acme/shop', branch: 'feat/SHOP-412-saved-card', commit: 'abc1234', pull_request: '412', dirty: false };
const log = (step, detail = '') => console.log(`  ${String(step).padEnd(46)} ${detail}`);

console.log(`\nSimulated testing session\n  state: ${stateDir}\n`);

/* ------------------------------------------------------------------ 1. session */

const session = state.startSession({
  request: 'Test PR #412 — saved-card support in guest checkout',
  trigger: 'pull-request',
  git: GIT,
  goals: [{
    goal: 'Validate the saved-card payment flow',
    target: 'src/checkout, server/payments',
    success_criteria: [
      'A saved card completes and creates exactly one order',
      'A declined card errors and creates no order',
      "A user cannot select another user's saved card",
    ],
  }],
});
log('session started', session.session_id);
state.setPhase('profile', 'repository profiled');

/* ------------------------------------------------------------------- 2. risk */

const assessment = risk.score({
  profile: 'security-critical',
  factors: {
    business_criticality: { value: 1.0, basis: 'checkout is the only revenue path', epistemic_class: 'observed' },
    security_sensitivity: { value: 0.9, basis: 'payment-method lookup reads session identity (stripe.ts:52)', epistemic_class: 'observed' },
    data_sensitivity: { value: 1.0, basis: 'stored card references and billing addresses', epistemic_class: 'observed' },
    change_magnitude: { value: 0.6, basis: '312 changed lines across 7 files (git diff --stat)', epistemic_class: 'observed' },
    coverage_deficit: { value: 0.8, basis: 'no test exercises the saved-card branch (grep across e2e/ and server/)', epistemic_class: 'observed' },
    irreversibility: { value: 0.9, basis: 'captures real payments; refunds are manual', epistemic_class: 'inferred' },
    change_frequency: { value: 0.7, basis: '31 commits to server/payments in 6 months', epistemic_class: 'observed' },
  },
});
log('risk scored', `${assessment.risk_score} ${assessment.risk_level} (confidence ${assessment.confidence})`);
state.setPhase('assess-risk');

/* ---------------------------------------------------------- 3. applicability */

const matrix = applicability.evaluate({
  signals: ['ui', 'web-ui', 'http-api', 'database', 'auth', 'authz', 'sessions', 'user-input',
    'payments', 'pii', 'external-integration', 'existing-tests', 'browser-tooling',
    'component-framework', 'ci', 'third-party-deps', 'migrations'],
  riskAssessment: assessment,
  coverage: { unit: 'substantial', e2e: 'partial', api: 'minimal', security: 'none', migration: 'none' },
  capabilities: { 'browser.explore': true, 'browser.run_deterministic_test': true, 'database.query': true },
  budgetMinutes: 150,
});
log('applicability evaluated', `${matrix.applicable.length} applicable, ${matrix.not_applicable.length} not, ${matrix.selected.length} selected`);
state.setPhase('classify');

/* ------------------------------------------------------- 4. browser decision */

const browserChoice = browser.decide({
  scenario: 'Saved-card checkout flow was changed; existing Playwright coverage is partial and the new branch has not been examined.',
  factors: {
    ui_known: 0.2, repeatability: 0.9, determinism_required: 0.7, exploratory_value: 0.8,
    ci_suitability: 0.6, business_criticality: 0.95, assertion_complexity: 0.7,
    execution_frequency: 0.8, existing_automation: 0.35, environment_stability: 0.7,
    evidence_requirements: 0.9, network_mocking_required: 0.5, maintenance_cost_tolerance: 0.6,
    tool_reliability: 0.7,
  },
  capabilities: { 'browser.explore': true, 'browser.run_deterministic_test': true, 'shell.run': true },
});
log('browser method chosen', `${browserChoice.selected} (confidence ${browserChoice.confidence})`);

const dec = decisions.record({
  question: 'How should the changed saved-card checkout UI be tested?',
  category: 'browser-method',
  context: { summary: browserChoice.reason[0], git: GIT },
  options: browserChoice.candidates.map((c) => ({
    id: c.id, label: c.label, score: c.score,
    ...(c.blocked_because.length ? { rejected_because: c.blocked_because.join(' ') } : {}),
  })),
  selected: browserChoice.selected,
  reason: browserChoice.reason,
  confidence: browserChoice.confidence,
  reversible: true,
  risk: { level: assessment.risk_level, score: assessment.risk_score, note: 'payment path with no coverage of the new branch' },
  downstreamEffect: ['An exploratory execution runs first', 'A committed spec is added to e2e/ if the scenario meets the conversion threshold'],
  policyRefs: [browserChoice.policy_ref],
  skillName: 'browser-testing',
});
log('decision recorded', dec.decision_id);
state.setPhase('plan');

/* ------------------------------------- 5. an unevidenced claim gets downgraded */

state.setPhase('execute');
const e0 = execution.start({ goal: 'Quick smoke of the checkout page', method: 'existing-suite', testCategory: 'smoke', git: GIT });
const downgraded = execution.finish(e0.execution_id, { status: 'PASSED', statusReason: 'Checkout works.', evidence: [] });
log('unevidenced PASSED claim', `${downgraded.record.status} (downgraded: ${downgraded.downgraded})`);

/* --------------------------------------------------- 6. a properly evidenced run */

const e1 = execution.start({
  goal: 'Baseline: full unit suite at head',
  method: 'existing-suite', testCategory: 'regression', git: GIT,
  environment: 'local', command: 'npm test', decisionId: dec.decision_id,
});
const ev1 = evidence.captureOutput({
  argv: 'npm test', cwd: '/repo', exitCode: 0, durationMs: 12480,
  stdout: 'Test Files  34 passed (34)\nTests  211 passed (211)', stderr: '',
  summary: 'vitest: 211/211 passed', executionId: e1.execution_id, git: GIT,
});
execution.finish(e1.execution_id, {
  status: 'PASSED',
  statusReason: 'vitest suite executed against abc1234; 211 tests passed, 0 failed.',
  evidence: [ev1.evidence_id],
  testResults: [
    { name: 'cart totals include tax', status: 'PASSED', file: 'src/cart.test.ts', test_case_id: 'TC-00001', validates_requirements: ['REQ-1'] },
    { name: 'payment intent rejects a negative amount', status: 'PASSED', file: 'server/payments/intent.test.ts', test_case_id: 'TC-00002', validates_requirements: ['REQ-2'] },
  ],
});
log('evidenced PASSED claim', 'PASSED, not downgraded');

/* ------------------------------------------- 7. a failing run, then a finding */

const e2 = execution.start({
  goal: "User A cannot select user B's saved card",
  method: 'api-client', testCategory: 'authn-authz', git: GIT,
  environment: 'local-docker', command: 'npm run test:api -- saved-cards', decisionId: dec.decision_id,
});
const ev2 = evidence.captureOutput({
  argv: 'npm run test:api -- saved-cards', cwd: '/repo', exitCode: 1, durationMs: 3120,
  stdout: "FAIL  saved card belonging to another user is not selectable\n  expected 403, received 200",
  summary: 'api: 11/12 passed, 1 failed', executionId: e2.execution_id, git: GIT,
});
const finished = execution.finish(e2.execution_id, {
  status: 'FAILED',
  statusReason: "GET /api/payment-methods/:id returned another user's card with HTTP 200.",
  evidence: [ev2.evidence_id],
  signals: ['assertion-mismatch', 'http-403'],
  testResults: [{ name: "saved card belonging to another user is not selectable", status: 'FAILED', file: 'test/api/saved-cards.test.ts', validates_requirements: ['REQ-3'] }],
});
log('failure classified', `${finished.record.failure_classification.class} (confidence ${finished.record.failure_classification.confidence})`);

const finding = defects.create({
  title: "Saved card belonging to another user is selectable and chargeable",
  kind: 'security-issue', severity: 'critical', confidence: 0.86, epistemicClass: 'observed',
  component: 'server/payments', environment: 'local-docker',
  summary: 'The payment-method lookup does not compare the record owner to the session user, so any authenticated user can select and charge a card saved by someone else.',
  reproduction: {
    preconditions: ['User A and user B both exist', 'User B has a saved card'],
    steps: ['Authenticate as user A', "Request GET /api/payment-methods/<user B's card id>", 'Observe the response'],
    expected: '403 Forbidden, or 404 if the design hides existence',
    actual: "200 OK with user B's card brand, last4 and billing postcode",
    reproducible: 'always', attempts: 3,
  },
  impact: 'Any authenticated user can enumerate and charge other users\' stored cards. Financial and personal data exposure.',
  git: GIT, evidence: [ev2.evidence_id], relatedRequirements: ['REQ-3'], executionId: e2.execution_id,
  recommendedAction: 'Add an ownership check in server/payments/stripe.ts:52 before returning or using a payment method.',
});
log('finding recorded', `${finding.finding_id} ${finding.severity}`);

// The same defect observed again, worded differently.
const dup = defects.create({
  title: "Saved  card belonging to another user IS selectable, and chargeable!",
  kind: 'security-issue', severity: 'critical', confidence: 0.86,
  component: 'server/payments',
  reproduction: { expected: '403 Forbidden, or 404 if the design hides existence', actual: "200 OK with user B's card brand, last4 and billing postcode" },
});
log('duplicate suppressed', `${dup.finding_id} -> duplicate_of ${dup.duplicate_of}`);

/* --------------------------------------- 8. a blocker that does not stop work */

const u1 = uncertainty.raise({
  question: 'Should payment E2E use a real provider sandbox key, or a mock at the HTTP boundary?',
  status: 'user-input-required',
  impact: 'cannot safely execute a real transaction; will not transact against a live key',
  affectedScope: ['payment-e2e'], blocksCategories: ['e2e'],
  nextAction: 'ask the user which environment and credentials to use',
  owner: 'user',
  independentWork: [
    'Ran the unit suite (211/211 at abc1234)',
    'Ran API tests against a mocked provider (11/12)',
    'Drafted e2e/payment.spec.ts so it is ready either way',
  ],
});
execution.recordNonExecution({
  goal: 'Payment E2E against the real provider',
  status: 'BLOCKED',
  reason: 'STRIPE_SECRET_KEY is unset; refusing to transact against a live key.',
  testCategory: 'e2e', uncertainties: [u1.id],
});
const partition = uncertainty.partitionWork([
  { id: 'payment-e2e', category: 'e2e' },
  { id: 'cart-unit', category: 'unit' },
  { id: 'api-authz', category: 'authn-authz' },
  { id: 'migration-forward', category: 'migration' },
]);
log('blocker raised', `${u1.id} — ${partition.runnable.length} runnable, ${partition.blocked.length} blocked`);

/* ------------------------------ 9. a not-applicable category, recorded properly */

execution.recordNonExecution({
  goal: 'Localisation testing',
  status: 'NOT_APPLICABLE',
  reason: 'No i18n resources exist in the repository; nothing is translated.',
  testCategory: 'localization',
});

/* --------------------------------------- 10. an interrupted execution, recovered */

const e3 = execution.start({ goal: 'Accessibility scan of the checkout pages', method: 'static-analysis', testCategory: 'accessibility', git: GIT });
state.recordInterruption({ kind: 'user', note: 'user asked to prioritise the authorisation defect' });
const recovery = state.recover();
log('recovery ran', `${recovery.orphaned_executions.length} execution(s) marked INTERRUPTED`);

/* ------------------------------------------------- 11. external writes, honestly */

const promo = defects.assessPromotion(finding.finding_id, { userAuthorised: true, authorisationQuote: 'yes, open a GitHub issue for that' });
log('promotion assessed', `may_file=${promo.may_file}`);

auth.recordWrite({
  system: 'github', action: 'github.create_issue', idempotencyKey: finding.fingerprint,
  target: 'acme/shop', confirmed: true, resultId: '#418',
  url: 'https://github.com/acme/shop/issues/418',
  authorisedBy: 'user-explicit', decisionId: dec.decision_id,
});
auth.recordWrite({
  system: 'jira', action: 'jira.comment', idempotencyKey: 'SHOP-412:plan',
  target: 'SHOP-412', confirmed: false,
  error: 'Atlassian connector not authorised in this session',
  authorisedBy: 'user-explicit',
});
log('external writes recorded', '1 confirmed, 1 NOT confirmed');

const assignAttempt = auth.check({ action: 'github.assign_issue', target: '#418', userAuthorised: true, assignee: null });
log('assignment without a name', `allowed=${assignAttempt.allowed}`);

// A distinct refusal from the one above: this is not "you forgot to name the account", it
// is "this action is refused by default, regardless of what the user says here" -- the
// agent cannot self-authorise around it even with userAuthorised: true.
const mergeAttempt = auth.check({ action: 'github.merge_pr', target: '#418', userAuthorised: true });
log('merge refused by default', `allowed=${mergeAttempt.allowed} (${mergeAttempt.level})`);

/* ----------------------------------------------------------- 12. remaining work */

state.update((s) => {
  s.remaining_work = [
    { item: 'Payment E2E against a provider sandbox', status: 'BLOCKED', reason: 'awaiting an environment decision', blocked_by: u1.id },
    { item: 'Accessibility scan of the checkout pages', status: 'INTERRUPTED', reason: 'user redirected mid-run; must restart from the beginning' },
    { item: 'Migration rollback compatibility check', status: 'DEFERRED', reason: 'deferred for budget; the forward migration was verified' },
  ];
  s.goals[0].status = 'PARTIAL';
  s.goals[0].success_criteria[2].status = 'FAILED';
  s.goals[0].success_criteria[2].evidence = [ev2.evidence_id];
  s.goals[0].success_criteria[2].execution_id = e2.execution_id;
  return s;
});
state.setPhase('document');

/* ---------------------------------------------------------------- 13. the report */

const { report, markdown, markdown_path } = reporting.generate({
  riskAssessment: assessment,
  applicability: matrix.matrix,
  plan: { requirements: [{ id: 'REQ-1' }, { id: 'REQ-2' }, { id: 'REQ-3' }], scenarios: [] },
  recommendations: [
    'Add the ownership check in server/payments/stripe.ts:52 before anything else ships.',
    'Decide the payment E2E environment so the drafted spec can run.',
    'Add a rollback-compatibility check to CI — the forward migration passes but the previous app version was not tested against the new schema.',
  ],
});
log('report generated', report.report_id);
log('  overall status', report.executive_summary.overall_status);
log('  false confidence rate', String(report.integrity.false_confidence_rate));
log('  not tested items', String(report.executive_summary.what_was_not_tested.length));

const untested = query('what-remains-untested');
log('traceability', `${untested.uncovered.length} requirement(s) uncovered: ${untested.uncovered.join(', ') || 'none'}`);

/* --------------------------------------------------------------- 14. emit copies */

const emit = arg('emit');
if (emit) {
  fs.mkdirSync(emit, { recursive: true });
  const write = (name, content) => {
    fs.writeFileSync(path.join(emit, name), content, 'utf8');
    console.log(`  emitted ${path.join(emit, name)}`);
  };
  const banner = [
    '<!--',
    'GENERATED ARTEFACT — illustrative example.',
    '',
    'Produced by `node scripts/demo-session.mjs`, which drives the engines through a',
    'simulated session. The software described does not exist and no real testing occurred.',
    'It is included so you can see the exact shape the system produces, rather than a',
    'hand-written approximation of it.',
    '-->',
    '',
  ].join('\n');

  console.log('');
  write('example-report.md', banner + markdown);
  write('example-report.json', `${JSON.stringify(report, null, 2)}\n`);
  write('example-execution.json', `${JSON.stringify(state.get('executions', e2.execution_id), null, 2)}\n`);
  write('example-decision.json', `${JSON.stringify(state.get('decisions', dec.decision_id), null, 2)}\n`);
  write('example-finding.json', `${JSON.stringify(state.get('findings', finding.finding_id), null, 2)}\n`);
  write('example-uncertainty.json', `${JSON.stringify(state.get('uncertainties', u1.id), null, 2)}\n`);
  const issue = defects.renderIssue(finding.finding_id);
  write('example-github-issue.md', `${banner}# ${issue.title}\n\n**Labels:** ${issue.labels.join(', ')}\n\n---\n\n${issue.body}\n`);
}

console.log(`\nReport markdown: ${markdown_path}`);
console.log(`State root:      ${stateDir}\n`);
